### ISSUE TITLE
extension seems to work fine on Windows

### ISSUE THREAD

**Issue by mpcjanssen** [etnadji/vim-epub#3]
If gnu unzip is in the executable path, the extensions seems to work fine (after removing some Windows checks)

I tested with the unzip from http://gnuwin32.sourceforge.net/packages/zip.htm

**Comment by etnadji** [comment]
Well, I finally saw your issue -_-
Sorry about that, I’m now mainly working on a Gitlab instance…
The README and the wiki have been edited from your contribution.
